Merge release_1.3.2 --> develop (#365)
* Add note on existing_str

* Refactor test_interface.rb into multiple files

* This test was trying to do too much; it became too large and unwieldy to use and troubleshoot.
* Refactor to use new test syntax (test_harness_run)
* File changes:
  *  deleted:    test_interface.rb
  *  new file:   interfacelib.rb
  *  new file:   test_interface_L2.rb
  *  new file:   test_interface_L3.rb
  *  new file:   test_interface_bdi.rb
  *  modified:   test_interface_capabilities.rb
  *  modified:   test_interface_stp.rb
  *  new file:   test_interface_svi.rb
  *  new file:   test_interface_private_vlan.rb

* renamed test_vlan_mapping.rb to test_interface_vlan_mapping.rb

* Only tested on n7k and n9k so far but there's a lot here and I wanted to get some eyes on the changes

* Platform tweaks for test_interface*

* test_interface: add skip_unless_supported plat checks

* Minor change to bail out of the test immediately if the platform does not apply

* test_interface_private_vlan: fix trunk assoc cleanup

* Found a bug on n9k where 'private-vlan association trunk' does not get cleaned up by 'default interface', which breaks this beaker test

* Created a workaround cleanup method that does 'no switchport'

* Tested on N9k-I3

* test_private_vlan: refactor, remove redundancies

* Refactored to use new test syntax; removed unnecessary/redundant tests and some that didn't test anything
* This test suffers from the same idempotency bug as the interface private-vlan code; it will require the same kind of fix

* Tested on n9k-I3, N7

* Bump version number.

* Add testing for switchport_autostate_exclude

* Remove old and redudant access_vlan tests

* Remove old style beaker tests

* normalize_range_array for puppet

This is the puppet counter-part to NU. The notes below are copied from: https://github.com/cisco/cisco-network-node-utils/pull/400
The main difference between these is a default check in Utils.normalize_range_array and that there's no Utils.dash_range_to_elements since that's not needed in puppet.

* The motivation for this change was finding yet another array normalizer in the private vlan code so these changes are initially meant to address fixes there. IMO our range summarize methods were getting a bit long and difficult to maintain; these new methods will hopefully simplify things somewhat.

  * The main problem these methods are trying to solve is reconciling manifest inputs with getter results when there are overlapping ranges; e.g.:
  * '2-5, 9, 4-6'     needs to be ['2-6', '9']
  * ['2', '3', '4-6'] needs to be ['2-6']
  * ['2', '3', '4']   needs to be ['2-4']

* It's fairly easy to merge the ranges if they are actual ruby ranges instead of the dash-syntax ranges, so the new methods just convert to ruby ranges, merge, and convert back.

* Tested on n9k. Additional testing coming on the other platforms, as well well as demo, Readme, etc.

* bgp_af l2vpn

* Fix demo_bgp

* Fix additional_paths_install

* New beaker style vlan tests

* l2vpn/evpn support

* l2vpn/evpn support

* exclude n3k

* review comments

* Review comments

* cisco_interface: deprecate private_vlan*

* private_vlan refactor

* cisco_interface: private_vlan refactor

* Deprecated the private_vlan properties that were released with 1.3.0 and created new pvlan properties in their place.

* This is the companion to NU PR: https://github.com/cisco/cisco-network-node-utils/pull/406

* Updated Type, Provider, Beaker, Demo, README, and CHANGELOG.

* Currently only tested on N7, N9-i3. Additional testing in prog.

* readme and changelog

* readme and changelog

* Update README.md

* pvlan beaker fixups for 6k

* The 6k cli is strict about requiring vlan associations before allowing interface vlan association; therefore I added the dependencies to the test. I need to rerun the test on all the platforms to see if the platform check needs to be tweaked.

* Only tested on n6 so far

* Minor demo_interface changes

* Added some private-vlan dependency resources

* test_interface_private_vlan: n3k platform fixes

* demo manifest as well

* tested on n3-i4,n9-i2,n5,n9-i3,n7

* test_interface_stp needs vlan cleanup

* tested on n9-i3

* Re-add n8k doc references

* Fix some N8k references

* Add N8k back to support table

* Remove extra property

* Fix spacing in rotate property

* anycast_gateway platform checks

* Restrict the anycast test to n9k only

* Tested on n3,n7,n9-i2,n9-i3

* test_interface_service_vni script fixes

* Some cleanup / setup was insufficient

* :non_default was not getting run

* This is only supported on n7k; tested on n7k.

* test_vrf: f3 dependencies

* N7k needs an f3-only vdc for route_distinguisher

* tested on n7

* test_vrf_af: add f3 dependency for 7k

* tested on n7k

* Update README-agent-install.md

* Update README.md

* test_vlan/test_private_vlan: add f3 deps

* Tested on n7

* test_vxlan_vtep*: add f3 deps

* Tested on n7

* Refactor package provider to use rpm - qip (#328)

* Replace regexp with rpm -qip

* patching demo updates

* Updated fail message

* Update demo_patching.pp

* Add back rpm filename regexp support (#329)

* Add back rpm filename regexp support

* Remove debugs

* Update README.md

* interface svi fix

* Remove explicit anycast config

* anycast-gateway-mac is a required dependency; a recent commit added an explicit call to the test file to set this up; BUT we already had existing code for doing this that was part of interfacelib.rb

* The interfacelib code was returning early because of /unless/if/

* Tested on n9-i4

* test_interface_L2 should reset sys_def_switchport

* This test sets the system default switchport state to true but it should reset it to false when it's finished.

* Tested on n9-i4

* test_vxlan_vtep_vni: suppress_uuc broken

* There was a platform exception that tried to add this property using the new test syntax; however this test file uses an older syntax.

* Added an nv overlay hw support check (my n6k does not support nv overlay)

* Tested on n6

* README-agent-install: doc cleanup (#330)

* README-agent-install: doc cleanup

* This doc has had a lot of misc updates in the past so I tried to streamline the content somewhat and organize the sections into discrete steps.

* A couple of things that need a closer look:
 * The RPM table may need updating to reflect the GS fix coming out any day
 * The auto-install section for cisco_node_utils gem is a little weak. I'm not sure if I referenced the correct pp file and used the right directory target.

* README-agent-install.md: Cleanup node-utils section

* README-agent-install.md: fix broken links

* Review comments addressed

* All addressed except for the GS RPM comment.

* README-agent-install: GS RPM v1.5 tested

* Add markdown syntax flags

* README.md cleanup for 1.3.2 (#335)

* Move Document Workflow Map to Documentation Guide table

* README: Move Limitations into Platform Support

* Add Legend & tables

* README: Update Usage section

* README: Move platform support section after resource ref tables

* README.md: minor text change

* URL change: /develop/master/

* Addressed remaining PR comments

* /develop/master/ URL fixup

* test_vdc: fix for non-F3 testbeds (#336)

* test_vdc: fix for non-F3 testbeds

* Updated this test to work with non-F3 N7k testbeds.
  * Initially set the VDC module-type to default state
  * Then set module-type to F3 and test
  * There's no great way to know which way to leave the module-type when this test completes, so:
    * Reset module-type to default for non-F3 testbeds since leaving it as F3 means the device won't have any usable interfaces
    * Noop for F3 testbeds so that it leaves their F3 still usable

* Tested on n6, n7-non-F3

* beaker tests: add F3 dependencies

* vdc, bridge-domain tests

* tested on n6, n7-non-F3

* Fix vxlan_vtep_vni suppress_uuc prop (#341)

* Readme.md changes for itd_service (#346)

* itd_service pre requisite

* cleanup

* cleanup

* review comment

* review comment

* review comment

* Add n8k reference to CHANGELOG

* command_config: undefined method 'previous' (#358)

* Symptom: Simple cc manifest with a faulty line of config:

cisco_command_config { 'interface':
   command  => '
     interface loopback42
     ipv6 pim foo
   '
}

When puppet agent runs the cc provider drops into a rescue which should first print out the parts of the config that were successfully processed and then do a raise, but instead we see:

```
  Error: undefined method 'previous' for #<Cisco::CliError:0x0000000460ac08>
```

* Analysis: `client.rb` was refactored a few months ago, wherein the `previous` hash key was renamed to `successful_input`. The cc providers (both puppet & chef) never got updated with the new key name.
  * Ref: https://github.com/cisco/cisco-network-node-utils/blob/develop/lib/cisco_node_utils/client/nxapi/client.rb#L285

* Testing:

```
Linux# puppet agent -t --debug
 ...
Info: Cisco_command_config[interface](provider=cisco): Successfully updated:
interface loopback42
Error: The command 'ipv6 pim foo' was rejected with error:
% Invalid command

Error: /Stage[main]/Main/Node[default]/Cisco_command_config[interface]/command: change from  to interface loopback42
ipv6 pim foo
 failed: The command 'ipv6 pim foo' was rejected with error:
% Invalid command

```

* New overlay_global behaviors (#360)

* DME changes for l2rib properties resulted in removal of the 'default' keyword from the cli:

    `l2rib dup-host-mac-detection default`

* Prior to this change, 'default' was the only way to reset the host_moves & timeout properties back to default; there was/is no 'no' command, so the only way to reset it now is to re-enter the command with the default values.

* This change necessitates changes to the setter, minitest, and beaker. I also changed the default values to actual integer values instead of empty strings.

* Tested minitest & beaker for: n9-edev,n9-I4,n5,n6. Skips for n3 (normal) and n7 (requires F3 card).

* Remove vsh code (#361)

* Fix cisco_aaa* 'TACACS+ group delete denied, group is in use' issue (#362)

* Added setup and cleanup steps

* Add back needed autorequires

* Added cleanup and teardown calls

* Refactor setup/cleanup

* Remove debug causing beaker tests to error out

* Fix cisco_tacacs* 'TACACS+ group delete denied, group is in use' (#363)

* Added setup and cleanup steps

* Add back needed autorequires

* Added cleanup and teardown calls

* Refactor setup/cleanup

* Remove debug causing beaker tests to error out

* Add setup/cleanup steps

* Fix netdev tacacs* 'TACACS+ group delete denied, group is in use' (#364)

* Added setup and cleanup steps

* Add back needed autorequires

* Added cleanup and teardown calls

* Refactor setup/cleanup

* Remove debug causing beaker tests to error out

* Add setup/cleanup steps

* Add setup/cleanup steps

* Fixed merge issue